<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net45;net46;net47;netstandard2.0;net8</TargetFrameworks>
    <BuildInParallel>false</BuildInParallel>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>1.0.0-beta011</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Product>Skybrud.Social</Product>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Description>API service implementation for the Toggl API.</Description>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Skybrud.Social.Toggl</PackageId>
    <PackageTags>Toggl, Skybrud, Social, JSON, Limbo, Integration</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://social.skybrud.dk/toggl/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/abjerner/Skybrud.Social.Toggl</RepositoryUrl>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="BuildDate" Value="$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmmss`))" />
  </ItemGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" Version="1.1.58" />
    <PackageReference Include="Skybrud.Essentials.Http" Version="1.2.0" />
    <PackageReference Include="Nullable" Version="1.3.1" PrivateAssets="all" />
  </ItemGroup>

  <!-- Include and exclude other files -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
    <Content Include="../../LICENSE.md" Pack="false" />
    <Content Include="../../README.md" Pack="false" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>